apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-es-0001 
  labels: 
    es-non-dynamic-storage-pv: "true"
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /exports/nfs/logging/vol1
    server: node-0.rajranjabastion.lab.pnq2.cee.redhat.com
  persistentVolumeReclaimPolicy: Retain
#  storageClassName: es-non-dynamic-storage-classa